### ISSUE TITLE
Bug in performWithArgumentsInSuperclass primitive?

### ISSUE THREAD

**Issue by charig** [smarr/TruffleSOM#7]
https://github.com/charig/TruffleMATE/commit/f8fff7bfffbe84f63129cc934f4e0b48dabffff1

**Comment by smarr** [comment]
Could be. Do you have a test for it :)

**Comment by charig** [comment]
Well actually i have but is quite related with lot of Mate stuff. I think the error would appear just calling the primitive since it is specializing on an Object[] instead of a St Array. I guess it is call from non place. Nevertheless, i can probably attach a test tomorrow if needed.

**Comment by smarr** [comment]
This issue was moved to SOM-st/TruffleSOM#1
